#!/bin/bash

N_POKEMON=1871

usage() {
  echo "
  Description: Prints a Pokémon with a message.
  Usage:
	$(basename $0) [-p POKÉMON] [-f COWFILE] [-w COLUMN] [-lnNt] [-h] [MESSAGE]

  Options:
    -p, --pokemon POKÉMON_NAME
      CHOOSE a Pokémon by name.
    -f, --file COWFILE
      CHOOSE a Pokémon cowfile.
    -w, --word-wrap COLUMN
      Specifies roughly where the message should be wrapped.
    -n, --no-wrap
      Do not wrap the message.
    -l, --list
      List all the Pokémon available.
    -N, --no-name
      Do not print the name of the Pokémon.
    -h, --help
      Display this usage message.
    message
      The message for chosen Pokémon to say. If this is not provided the Pokémon will read from STDIN
"
  exit 0
}

list_pokemon() {
	echo "Pokémon available in $HOME/.pokemonsay/cows/ :"
	find $HOME/.pokemonsay/cows/ -iname "*.cow"
	exit 0
}

# Disable wrapping by default
WORD_WRAP=""
DISABLE_NAME=false

while getopts ":p:f:wnNlh" Option ; do
	case $Option in
		f ) COWFILE="$OPTARG"      ;;
		p ) I_CHOOSE="$OPTARG"     ;;
		w ) WORD_WRAP="-W $OPTARG" ;;
		n ) WORD_WRAP="-n"         ;;
		N ) DISABLE_NAME=true      ;;
		l ) list_pokemon           ;;
		h ) usage                  ;;
		* ) echo "Unimplemented option chosen." && usage ;;
	esac
done
shift $(($OPTIND - 1))
MESSAGE="${1}"

# Define which pokemon should be displayed, then call cowsay or cowthink
# TODO: restore cowthink after fine-tuning cowsay
if [ -n "$I_CHOOSE" ]; then
	fpath=$(find $HOME/.pokemonsay/cows/ -type f -iname "$I_CHOOSE.cow")
  if [ -z "${fpath:-}" ]; then
    echo "Unable to find Pokémon matching name $I_CHOOSE.cow in $HOME/.pokemonsay/cows/"
    exit 1
  fi
	cowsay -f "$fpath" $WORD_WRAP "$MESSAGE"
elif [ -n "$COWFILE" ]; then
	cowsay -f "$COWFILE" $WORD_WRAP "$MESSAGE"
else
	INDEX=$[ $RANDOM % $N_POKEMON ]
	I_CHOOSE_FPATH=$(find $HOME/.pokemonsay/cows/ -type f -iname "*.cow" | head -n $INDEX | tail -n 1)
	I_CHOOSE=$(basename $I_CHOOSE_FPATH)
	I_CHOOSE=${I_CHOOSE%.cow}
	cowsay -f "$I_CHOOSE_FPATH" $WORD_WRAP "$MESSAGE"
fi

# Write the pokemon name, unless requested otherwise.
$DISABLE_NAME || echo $I_CHOOSE

